services:
  db:
    image: postgres:latest
    build:
      context: database
      dockerfile: Dockerfile
    container_name: my_postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - application_network
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./database/vehicules-commercialises.csv:/docker-entrypoint-initdb.d/vehicules-commercialises.csv:ro

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: "Europe/Paris"

  app_findcar:
    build:
      context: server/backend-findcar
      dockerfile: Dockerfile
    container_name: backend_findcar
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - application_network
    ports:
      - "5000:5000"
    volumes:
      - ./server/backend-findcar:/app

  app_pollution:
    build:
      context: server/backend-pollution
      dockerfile: Dockerfile
    container_name: backend_pollution
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - application_network
    ports:
      - "5001:5000"
    volumes:
      - ./server/backend-pollution:/app

  frontend:
    build: ./server/frontend_bis
    container_name: frontend
    restart: always
    depends_on:
      - app_findcar
      - app_pollution
    ports:
      - "8080:80"
    networks:
      - application_network

volumes:
  postgres_data:
    driver: local

networks:
  application_network: