version: "3.8"

services:
  db:
    image: postgres:latest
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: my_postgres_db
    restart: always
    env_file:
      - ./database/.env
    ports:
      - "5432:5432"
    networks:
      - application_network
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./database/vehicules-commercialises.csv:/docker-entrypoint-initdb.d/vehicules-commercialises.csv:ro

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: "Europe/Paris"

  app:
    build:
      context: ./server/backend-findcar
      dockerfile: Dockerfile
    container_name: backend_findcar
    restart: always
    depends_on:
      - db
    env_file:
      - ./server/backend-findcar/.env
    networks:
      - application_network
    ports:
      - "5000:5000"
    volumes:
      - ./server/backend-findcar:/app

volumes:
  postgres_data:
    driver: local

networks:
  application_network: