apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-pollution
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-pollution
  template:
    metadata:
      labels:
        app: backend-pollution
    spec:
      containers:
        - name: backend-pollution
          image: linspecteur/backend-pollution:v1
          ports:
            - containerPort: 5001
          env:
            - name: POSTGRES_DB
              value: "carsdatabase"
            - name: POSTGRES_USER
              value: "userx"
            - name: POSTGRES_PASSWORD
              value: "RrOppY6%wCV!J0^!l@"
            - name: POSTGRES_HOST
              value: "postgres-service"
            - name: POSTGRES_PORT
              value: "5432"
            - name: FINDCAR_HOST
              value: "backend-findcar"
            - name: FINDCAR_PORT
              value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-pollution
spec:
  selector:
    app: backend-pollution
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
